version: '3.7'

services:
  web:
    image: nginx:latest
    container_name: template
    ports:
      - '80:80'
    volumes:
      - ./src:/src
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - template-network
    depends_on:
      - php
  php:
    container_name: template-php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
        - ./src:/src
    networks:
      - template-network
    depends_on:
      - db
  db:
    container_name: template-db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: template
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    networks:
      - template-network
  
networks:
  template-network:
    driver: bridge
  