version: '3.7'

services:
  web:
    image: nginx:latest
    container_name: sqlsa
    ports:
      - '80:80'
    volumes:
      - ./src:/src
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sqlsa-network
    depends_on:
      - php
  php:
    container_name: sqlsa-php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
        - ./src:/src
    networks:
      - sqlsa-network
    depends_on:
      - db
  db:
    container_name: sqlsa-db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: sqlsa
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    networks:
      - sqlsa-network
  
networks:
  sqlsa-network:
    driver: bridge
  